/*
 * MCreator (https://mcreator.net/)
 * Copyright (C) 2020 Pylo and contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package net.mcreator.ui.action.impl.workspace;

import net.mcreator.element.GeneratableElement;
import net.mcreator.generator.GeneratorFile;
import net.mcreator.gradle.GradleTaskFinishedListener;
import net.mcreator.io.FileIO;
import net.mcreator.io.writer.ClassWriter;
import net.mcreator.plugin.modapis.ModAPIManager;
import net.mcreator.ui.MCreator;
import net.mcreator.ui.action.ActionRegistry;
import net.mcreator.ui.action.impl.gradle.GradleAction;
import net.mcreator.ui.dialogs.ProgressDialog;
import net.mcreator.ui.init.L10N;
import net.mcreator.ui.init.UIRES;
import net.mcreator.workspace.WorkspaceUtils;
import net.mcreator.workspace.elements.ModElement;
import net.mcreator.workspace.elements.TagElement;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import javax.annotation.Nullable;
import javax.swing.*;
import java.io.File;
import java.util.*;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

public class RegenerateCodeAction extends GradleAction {

	private static final Logger LOG = LogManager.getLogger("Code Regenerate");

	public RegenerateCodeAction(ActionRegistry actionRegistry) {
		super(actionRegistry, L10N.t("action.workspace.regenerate_and_build"),
				e -> regenerateCode(actionRegistry.getMCreator(), false, true));
		setIcon(UIRES.get("16px.regencode"));
	}

	public static void regenerateCode(MCreator mcreator, boolean warnLockedCode, boolean warnMissingDefinitions) {
		regenerateCode(mcreator, warnLockedCode, warnMissingDefinitions, null);
	}

	public static void regenerateCode(MCreator mcreator, boolean warnLockedCode, boolean warnMissingDefinitions,
			@Nullable GradleTaskFinishedListener taskSpecificListener) {
		ProgressDialog dial = new ProgressDialog(mcreator, L10N.t("dialog.workspace.regenerate_and_build.title"));
		Thread thread = new Thread(() -> {
			ProgressDialog.ProgressUnit p0 = new ProgressDialog.ProgressUnit(
					L10N.t("dialog.workspace.regenerate_and_build.progress.removing_autogenerated_code"));
			dial.addProgressUnit(p0);

			WorkspaceUtils.removeAutoGeneratedCode(mcreator.getWorkspace(), p0);

			for (Map.Entry<TagElement, ArrayList<String>> tag : mcreator.getWorkspace().getTagElements().entrySet()) {
				tag.getValue().removeIf(TagElement::isEntryManaged);
			}

			p0.markStateOk();

			ProgressDialog.ProgressUnit p10 = new ProgressDialog.ProgressUnit(
					L10N.t("dialog.workspace.regenerate_and_build.progress.loading_mod_elements"));
			dial.addProgressUnit(p10);
			Collection<ModElement> modElementsOld = mcreator.getWorkspace().getModElements();
			int modstoload = modElementsOld.size();
			int i = 0;
			for (ModElement mod : modElementsOld) {
				mod.getGeneratableElement();
				p10.setPercent((int) (i / (float) modstoload * 100));
				i++;
			}
			p10.markStateOk();

			ProgressDialog.ProgressUnit p1 = new ProgressDialog.ProgressUnit(
					L10N.t("dialog.workspace.regenerate_and_build.progress.regenerating_code"));
			dial.addProgressUnit(p1);

			Set<ModElement> skippedElements = new HashSet<>(0);
			boolean skipAll = !warnMissingDefinitions;
			boolean hasLockedElements = false;

			List<GeneratableElement> generatableElementsToSave = new ArrayList<>();
			Set<File> filesToReformat = new HashSet<>();

			final List<ModElement> mods = new ArrayList<>(mcreator.getWorkspace().getModElements());
			final int n = mods.size();
			modstoload = n;

			final GeneratableElement[] ges = new GeneratableElement[n];
			for (int k = 0; k < n; k++) {
				try {
					ges[k] = mods.get(k).getGeneratableElement();
				} catch (Exception e) {
					ges[k] = null;
					LOG.error("Failed to regenerate: {}", mods.get(k).getName(), e);
				}
			}

			try {
				mcreator.getGenerator().getTemplateGeneratorFromName("templates");
			} catch (Exception e) {
				LOG.debug("Template generator pre-warm skipped: {}", e.getMessage());
			}

			@SuppressWarnings("unchecked")
			final List<GeneratorFile>[] genFiles = new List[n];
			final AtomicInteger progressCounter = new AtomicInteger(0);
			final int modstoloadF = modstoload;
			IntStream.range(0, n).parallel().forEach(idx -> {
				int done = progressCounter.incrementAndGet();
				p1.setPercent((int) (done / (float) modstoloadF * 100));
				GeneratableElement ge = ges[idx];
				if (ge == null)
					return;
				try {
					genFiles[idx] = mcreator.getGenerator().generateElement(ge, false, false);
				} catch (Exception e) {
					LOG.error("Failed to regenerate: {}", mods.get(idx).getName(), e);
				}
			});

			for (i = 0; i < n; i++) {
				ModElement mod = mods.get(i);

				if (mod.isCodeLocked()) {
					hasLockedElements = true;
				}

				try {
					GeneratableElement generatableElement = ges[i];
					if (generatableElement == null) {
						LOG.warn("Failed to regenerate: {} as it has no generatable element", mod.getName());

						if (!skipAll) {
							int opt = JOptionPane.showOptionDialog(mcreator,
									L10N.t("dialog.workspace.regenerate_and_build.error.failed_to_import.message",
											mod.getName(), skippedElements.size()),
									L10N.t("dialog.workspace.regenerate_and_build.error.failed_to_import.title"),
									JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null, new String[] {
											L10N.t("dialog.workspace.regenerate_and_build.error.failed_to_import.option.skip_one"),
											L10N.t("dialog.workspace.regenerate_and_build.error.failed_to_import.option.skip_all") },
									0);
							if (opt == 1)
								skipAll = true;
						}
						skippedElements.add(mod);
						continue;
					}

					LOG.debug("Regenerating {} mod element: {}", mod.getType().getReadableName(), mod.getName());

					List<GeneratorFile> generatedFiles = genFiles[i] != null ? genFiles[i] : new ArrayList<>();
					mcreator.getGenerator().applyFSTasks(generatableElement, generatedFiles, false);

					if (!mod.isCodeLocked()) {
						filesToReformat.addAll(
								generatedFiles.stream().map(GeneratorFile::getFile).collect(Collectors.toSet()));
					}

					mcreator.getModElementManager().storeModElementPicture(generatableElement);

					generatableElement.getModElement().reinit(mcreator.getWorkspace());

					generatableElement.getModElement().getMCItems().forEach(mcItem -> mcItem.icon.getImage().flush());

					generatableElementsToSave.add(generatableElement);
				} catch (Exception e) {
					LOG.error("Failed to regenerate: {}", mod.getName(), e);
				}
			}

			generatableElementsToSave.parallelStream().forEach(mcreator.getModElementManager()::storeModElement);

			if (warnMissingDefinitions && !skippedElements.isEmpty()) {
				skippedElements.forEach(el -> {
					try {
						mcreator.getWorkspace().removeModElement(el);
					} catch (Exception ignored) {
					}
				});
				JOptionPane.showMessageDialog(dial,
						L10N.t("dialog.workspace.regenerate_and_build.warning.skipped_import_of.message",
								skippedElements.size()),
						L10N.t("dialog.workspace.regenerate_and_build.warning.skipped_import_of.title"),
						JOptionPane.WARNING_MESSAGE);
			}

			if (warnLockedCode && hasLockedElements)
				JOptionPane.showMessageDialog(dial,
						L10N.t("dialog.workspace.regenerate_and_build.warning.elements_with_locked_code.message"),
						L10N.t("dialog.workspace.regenerate_and_build.warning.elements_with_locked_code.title"),
						JOptionPane.WARNING_MESSAGE);

			p1.markStateOk();

			ProgressDialog.ProgressUnit p2 = new ProgressDialog.ProgressUnit(
					L10N.t("dialog.workspace.regenerate_and_build.progress.regenerating_workspace_and_resources"));
			dial.addProgressUnit(p2);

			mcreator.getGenerator().runResourceSetupTasks();
			mcreator.getGenerator().generateBase(false);
			mcreator.reloadWorkspaceTabContents();

			ModAPIManager.deleteAPIs(mcreator.getWorkspace(), mcreator.getWorkspaceSettings());

			p2.markStateOk();

			ProgressDialog.ProgressUnit p22 = new ProgressDialog.ProgressUnit(
					L10N.t("dialog.workspace.regenerate_and_build.progress.reformating_code"));
			dial.addProgressUnit(p22);

			int ftfCount = filesToReformat.size();
			ClassWriter.formatAndOrganiseImportsForFiles(mcreator.getWorkspace(), filesToReformat,
					idx -> p22.setPercent((int) (((float) idx / (float) ftfCount) * 100.0f)));

			p22.markStateOk();

			ProgressDialog.ProgressUnit p23 = new ProgressDialog.ProgressUnit(
					L10N.t("dialog.workspace.regenerate_and_build.progress.clean_up_workspace"));
			dial.addProgressUnit(p23);

			FileIO.removeEmptyDirs(mcreator.getGenerator().getSourceRoot());
			FileIO.removeEmptyDirs(mcreator.getGenerator().getResourceRoot());

			new File(mcreator.getGenerator().getResourceRoot(), "MCreator-README.txt").delete();

			p23.markStateOk();

			ProgressDialog.ProgressUnit p3 = new ProgressDialog.ProgressUnit(
					L10N.t("dialog.workspace.regenerate_and_build.progress.rebuilding_workspace"));
			dial.addProgressUnit(p3);

			mcreator.getGradleConsole().markRunning();
			try {
				mcreator.getGenerator().generateBase();
				mcreator.getGradleConsole().exec("build", taskSpecificListener);
			} catch (Exception e) {
				LOG.error(e.getMessage(), e);
				mcreator.getGradleConsole().markReady();
			}

			mcreator.getWorkspace().markDirty();

			p3.markStateOk();

			dial.hideDialog();
		}, "RegenerateCode");
		thread.start();
		dial.setVisible(true);
	}

}
